baseURL = 'https://artur-rios.github.io/dotnet-logging/'
languageCode = 'en-us'
title = 'Dotnet Logging'
theme = 'hugo-theme-re-terminal'

[module]
  [[module.mounts]]
    source = 'coverage-report'
    target = 'static/coverage-report'

[params.logo]
  logoText = 'Dotnet Logging'

[menu]
  [[menu.main]]
    identifier = "author"
    name = "Author"
    url = "https://www.artur-rios.tech/"
  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/artur-rios/dotnet-logging"
  [[menu.main]]
    identifier = "test-coverage"
    name = "Test Coverage"
    url = "https://artur-rios.github.io/dotnet-logging/coverage-report"
